### ISSUE TITLE
Any possibility this plugin could be updated to work with sbt 1.x?

### ISSUE THREAD

**Issue by edwmurph** [fmonniot/sbt-redis-plugin#5]

**Comment by fmonniot** [comment]
That might be possible. I'll see what I can do this weekend.

**Comment by edwmurph** [comment]
That would be greatly appreciated thanks!

**Comment by fmonniot** [comment]
Version 0.6.0 have been released to bintray and is compatible with SBT 1.x

**Comment by edwmurph** [comment]
Thank you so much!
